---
- name: include os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: install common prerequisites
  become: true
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ powerline_prerequisites }}"

- name: include install tasks
  import_tasks: "install-{{ powerline_install_from }}.yaml"

- name: 
  ansible.builtin.blockinfile:
    path: "/home/{{ item.user }}/.bashrc"
    block: "{{ lookup('template', 'powerline.sh.j2') }}"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: '0644'
  with_items: "{{ powerline_users }}"
